// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RSSFeedsAPI.Data;

#nullable disable

namespace RSSFeedsAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230129172044_SetUp")]
    partial class SetUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("RSSFeedsAPI.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RSSFeedsAPI.Entities.Feed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Feed");
                });

            modelBuilder.Entity("RSSFeedsAPI.Entities.News", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FeedId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PubDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeedId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("RSSFeedsAPI.Entities.Feed", b =>
                {
                    b.HasOne("RSSFeedsAPI.Entities.AppUser", null)
                        .WithMany("Feeds")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("RSSFeedsAPI.Entities.News", b =>
                {
                    b.HasOne("RSSFeedsAPI.Entities.Feed", null)
                        .WithMany("News")
                        .HasForeignKey("FeedId");
                });

            modelBuilder.Entity("RSSFeedsAPI.Entities.AppUser", b =>
                {
                    b.Navigation("Feeds");
                });

            modelBuilder.Entity("RSSFeedsAPI.Entities.Feed", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
